export declare const autoSortProxyProvidersByHealth: any;
export declare const proxyProvidersSortMode: any;
export declare const showOnlyActiveProxyProviders: any;
export declare const showOnlyTrafficProxyProviders: any;
export declare const providerHealthFilter: any;
export declare const proxyProvidersProtoFilter: any;
export declare const providerHealthAvailable: any;
export declare const providerHealthActionsAvailable: any;
export declare const agentProvidersLoading: any;
export declare const agentProvidersOk: any;
export declare const agentProvidersError: any;
export declare const agentProvidersAt: any;
export declare const agentProviders: any;
export declare const agentProvidersSslCacheReady: any;
export declare const agentProvidersSslCacheFresh: any;
export declare const agentProvidersSslRefreshing: any;
export declare const agentProvidersSslRefreshPending: any;
export declare const agentProvidersSslCacheAgeSec: any;
export declare const agentProvidersSslCacheNextRefreshAtMs: any;
export declare const agentProvidersNextCheckAtMs: any;
export declare const agentProvidersJobStatus: any;
export declare const agentProvidersJobId: any;
export declare const panelSslNotAfterByName: any;
export declare const panelSslErrorByName: any;
export declare const panelSslUrlByName: any;
export declare const panelSslCheckedAt: any;
export declare const panelSslProbeError: any;
export declare const panelSslProbeLoading: any;
export declare const agentProviderByName: any;
export declare const fetchAgentProviders: (force?: boolean) => Promise<void>;
export declare const refreshSavedProviderSubscriptionSsl: () => Promise<{
    ok: boolean;
    error: string;
    checkedAtSec: number;
    items: any[];
}>;
export declare const refreshAgentProviderSslCache: () => Promise<any>;
export declare const probePanelSsl: (force?: boolean) => Promise<void>;
