export type ProxyFormModel = {
    originalName: string;
    name: string;
    type: string;
    server: string;
    port: string;
    udp: string;
    tfo: string;
    tls: string;
    skipCertVerify: string;
    sni: string;
    servername: string;
    clientFingerprint: string;
    network: string;
    dialerProxy: string;
    interfaceName: string;
    packetEncoding: string;
    uuid: string;
    password: string;
    cipher: string;
    flow: string;
    alpnText: string;
    wsPath: string;
    wsHeadersBody: string;
    grpcServiceName: string;
    grpcMultiMode: string;
    httpMethod: string;
    httpPathText: string;
    httpHeadersBody: string;
    smuxEnabled: string;
    smuxProtocol: string;
    smuxMaxConnections: string;
    smuxMinStreams: string;
    smuxMaxStreams: string;
    smuxPadding: string;
    smuxStatistic: string;
    wireguardIpText: string;
    wireguardIpv6Text: string;
    wireguardPrivateKey: string;
    wireguardPublicKey: string;
    wireguardPresharedKey: string;
    wireguardMtu: string;
    wireguardReservedText: string;
    wireguardWorkers: string;
    hysteriaUp: string;
    hysteriaDown: string;
    hysteriaObfs: string;
    hysteriaObfsPassword: string;
    tuicCongestionController: string;
    tuicUdpRelayMode: string;
    tuicHeartbeatInterval: string;
    tuicRequestTimeout: string;
    tuicFastOpen: string;
    tuicReduceRtt: string;
    tuicDisableSni: string;
    plugin: string;
    pluginOptsBody: string;
    realityPublicKey: string;
    realityShortId: string;
    extraBody: string;
};
export type ProxyReferenceInfo = {
    kind: 'group' | 'rule';
    text: string;
    key?: string;
    lineNo?: number;
};
export type ProxyGroupDisableImpact = {
    group: string;
    fallbackInjected: boolean;
};
export type ProxyDisableImpact = {
    impacts: ProxyGroupDisableImpact[];
    rulesTouched: number;
    ruleSamples: ProxyReferenceInfo[];
};
export type ParsedProxyEntry = {
    name: string;
    type: string;
    server: string;
    port: string;
    udp: string;
    tfo: string;
    tls: string;
    skipCertVerify: string;
    sni: string;
    servername: string;
    clientFingerprint: string;
    network: string;
    dialerProxy: string;
    interfaceName: string;
    packetEncoding: string;
    uuid: string;
    password: string;
    cipher: string;
    flow: string;
    alpn: string[];
    wsPath: string;
    wsHeadersBody: string;
    grpcServiceName: string;
    grpcMultiMode: string;
    httpMethod: string;
    httpPath: string[];
    httpHeadersBody: string;
    smuxEnabled: string;
    smuxProtocol: string;
    smuxMaxConnections: string;
    smuxMinStreams: string;
    smuxMaxStreams: string;
    smuxPadding: string;
    smuxStatistic: string;
    wireguardIp: string[];
    wireguardIpv6: string[];
    wireguardPrivateKey: string;
    wireguardPublicKey: string;
    wireguardPresharedKey: string;
    wireguardMtu: string;
    wireguardReserved: string[];
    wireguardWorkers: string;
    hysteriaUp: string;
    hysteriaDown: string;
    hysteriaObfs: string;
    hysteriaObfsPassword: string;
    tuicCongestionController: string;
    tuicUdpRelayMode: string;
    tuicHeartbeatInterval: string;
    tuicRequestTimeout: string;
    tuicFastOpen: string;
    tuicReduceRtt: string;
    tuicDisableSni: string;
    plugin: string;
    pluginOptsBody: string;
    realityPublicKey: string;
    realityShortId: string;
    extraBody: string;
    rawBlock: string;
    references: ProxyReferenceInfo[];
};
export declare const emptyProxyForm: () => ProxyFormModel;
export declare const proxyFormFromEntry: (entry: ParsedProxyEntry) => ProxyFormModel;
export declare const parseProxiesFromConfig: (value: string) => ParsedProxyEntry[];
export declare const upsertProxyInConfig: (value: string, form: ProxyFormModel) => string;
export declare const simulateProxyDisableImpact: (value: string, proxyName: string) => ProxyDisableImpact;
export declare const removeProxyFromConfig: (value: string, proxyName: string) => {
    yaml: string;
    impacts: ProxyGroupDisableImpact[];
    rulesTouched: number;
    ruleSamples: ProxyReferenceInfo[];
};
