import { UBUNTU_PATHS } from './project'

export const BACKEND_KINDS = {
  COMPATIBILITY_BRIDGE: 'compatibility-bridge',
  UBUNTU_SERVICE: 'ubuntu-service',
} as const

export const UBUNTU_BACKEND_ENDPOINTS = {
  status: '/api/status',
  health: '/api/health',
  version: '/api/version',
  capabilities: '/api/capabilities',
  metrics: '/api/system/metrics',
  resources: '/api/system/resources',
  services: '/api/system/services',
  network: '/api/system/network',
  connections: '/api/system/connections',
  logs: '/api/system/logs',
  providers: '/api/providers',
  providerChecks: '/api/providers/checks',
  providerChecksRun: '/api/providers/checks/run',
  providerRefresh: '/api/providers/refresh',
  providerSslCacheRefresh: '/api/providers/ssl-cache/refresh',
  providerSslCacheStatus: '/api/providers/ssl-cache/status',
  geoInfo: '/api/geo/info',
  geoUpdate: '/api/geo/update',
  geoHistory: '/api/geo/history',
  trafficOverview: '/api/traffic/overview',
  trafficClients: '/api/traffic/clients',
  trafficTopology: '/api/traffic/topology',
  qosStatus: '/api/qos/status',
  qosSet: '/api/qos/set',
  qosRemove: '/api/qos/remove',
  shapeSet: '/api/shape/set',
  shapeRemove: '/api/shape/remove',
  jobs: '/api/jobs',
  configActive: '/api/mihomo/config/active',
  configDraft: '/api/mihomo/config/draft',
  configHistory: '/api/mihomo/config/history',
  configValidate: '/api/mihomo/config/validate',
  configApply: '/api/mihomo/config/apply',
  configRollback: '/api/mihomo/config/rollback',
} as const

export const UBUNTU_BACKEND_CAPABILITIES = [
  'status',
  'health',
  'version',
  'capabilities',
  'metrics',
  'resources',
  'services',
  'network',
  'providers',
  'providerChecks',
  'providerChecksRun',
  'providerRefresh',
  'providerSslCacheRefresh',
  'providerSslCacheStatus',
  'geoInfo',
  'geoUpdate',
  'geoHistory',
  'trafficOverview',
  'trafficClients',
  'trafficTopology',
  'qosStatus',
  'qosSet',
  'qosRemove',
  'shapeSet',
  'shapeRemove',
  'jobs',
  'connections',
  'logs',
  'configActive',
  'configDraft',
  'configHistory',
  'configValidate',
  'configApply',
  'configRollback',
] as const

export const UBUNTU_BACKEND_FOUNDATION = {
  kind: BACKEND_KINDS.UBUNTU_SERVICE,
  endpoints: UBUNTU_BACKEND_ENDPOINTS,
  paths: UBUNTU_PATHS,
  capabilityKeys: UBUNTU_BACKEND_CAPABILITIES,
} as const
