export declare const BACKEND_KINDS: {
    readonly COMPATIBILITY_BRIDGE: "compatibility-bridge";
    readonly UBUNTU_SERVICE: "ubuntu-service";
};
export declare const UBUNTU_BACKEND_ENDPOINTS: {
    readonly status: "/api/status";
    readonly health: "/api/health";
    readonly version: "/api/version";
    readonly capabilities: "/api/capabilities";
    readonly metrics: "/api/system/metrics";
    readonly resources: "/api/system/resources";
    readonly services: "/api/system/services";
    readonly network: "/api/system/network";
    readonly connections: "/api/system/connections";
    readonly logs: "/api/system/logs";
    readonly providers: "/api/providers";
    readonly providerChecks: "/api/providers/checks";
    readonly providerChecksRun: "/api/providers/checks/run";
    readonly providerRefresh: "/api/providers/refresh";
    readonly providerSslCacheRefresh: "/api/providers/ssl-cache/refresh";
    readonly providerSslCacheStatus: "/api/providers/ssl-cache/status";
    readonly geoInfo: "/api/geo/info";
    readonly geoUpdate: "/api/geo/update";
    readonly geoHistory: "/api/geo/history";
    readonly trafficOverview: "/api/traffic/overview";
    readonly trafficClients: "/api/traffic/clients";
    readonly trafficTopology: "/api/traffic/topology";
    readonly qosStatus: "/api/qos/status";
    readonly qosSet: "/api/qos/set";
    readonly qosRemove: "/api/qos/remove";
    readonly shapeSet: "/api/shape/set";
    readonly shapeRemove: "/api/shape/remove";
    readonly jobs: "/api/jobs";
    readonly configActive: "/api/mihomo/config/active";
    readonly configDraft: "/api/mihomo/config/draft";
    readonly configHistory: "/api/mihomo/config/history";
    readonly configValidate: "/api/mihomo/config/validate";
    readonly configApply: "/api/mihomo/config/apply";
    readonly configRollback: "/api/mihomo/config/rollback";
};
export declare const UBUNTU_BACKEND_CAPABILITIES: readonly ["status", "health", "version", "capabilities", "metrics", "resources", "services", "network", "providers", "providerChecks", "providerChecksRun", "providerRefresh", "providerSslCacheRefresh", "providerSslCacheStatus", "geoInfo", "geoUpdate", "geoHistory", "trafficOverview", "trafficClients", "trafficTopology", "qosStatus", "qosSet", "qosRemove", "shapeSet", "shapeRemove", "jobs", "connections", "logs", "configActive", "configDraft", "configHistory", "configValidate", "configApply", "configRollback"];
export declare const UBUNTU_BACKEND_FOUNDATION: {
    readonly kind: "ubuntu-service";
    readonly endpoints: {
        readonly status: "/api/status";
        readonly health: "/api/health";
        readonly version: "/api/version";
        readonly capabilities: "/api/capabilities";
        readonly metrics: "/api/system/metrics";
        readonly resources: "/api/system/resources";
        readonly services: "/api/system/services";
        readonly network: "/api/system/network";
        readonly connections: "/api/system/connections";
        readonly logs: "/api/system/logs";
        readonly providers: "/api/providers";
        readonly providerChecks: "/api/providers/checks";
        readonly providerChecksRun: "/api/providers/checks/run";
        readonly providerRefresh: "/api/providers/refresh";
        readonly providerSslCacheRefresh: "/api/providers/ssl-cache/refresh";
        readonly providerSslCacheStatus: "/api/providers/ssl-cache/status";
        readonly geoInfo: "/api/geo/info";
        readonly geoUpdate: "/api/geo/update";
        readonly geoHistory: "/api/geo/history";
        readonly trafficOverview: "/api/traffic/overview";
        readonly trafficClients: "/api/traffic/clients";
        readonly trafficTopology: "/api/traffic/topology";
        readonly qosStatus: "/api/qos/status";
        readonly qosSet: "/api/qos/set";
        readonly qosRemove: "/api/qos/remove";
        readonly shapeSet: "/api/shape/set";
        readonly shapeRemove: "/api/shape/remove";
        readonly jobs: "/api/jobs";
        readonly configActive: "/api/mihomo/config/active";
        readonly configDraft: "/api/mihomo/config/draft";
        readonly configHistory: "/api/mihomo/config/history";
        readonly configValidate: "/api/mihomo/config/validate";
        readonly configApply: "/api/mihomo/config/apply";
        readonly configRollback: "/api/mihomo/config/rollback";
    };
    readonly paths: {
        readonly activeConfig: "/etc/mihomo/config.yaml";
        readonly stateRoot: "/var/lib/ultra-ui-ubuntu/";
        readonly configRoot: "/var/lib/ultra-ui-ubuntu/config/";
        readonly logsRoot: "/var/log/ultra-ui-ubuntu/";
        readonly mihomoLog: "/var/log/mihomo/mihomo.log";
        readonly agentEnv: "/etc/ultra-ui-ubuntu/agent.env";
    };
    readonly capabilityKeys: readonly ["status", "health", "version", "capabilities", "metrics", "resources", "services", "network", "providers", "providerChecks", "providerChecksRun", "providerRefresh", "providerSslCacheRefresh", "providerSslCacheStatus", "geoInfo", "geoUpdate", "geoHistory", "trafficOverview", "trafficClients", "trafficTopology", "qosStatus", "qosSet", "qosRemove", "shapeSet", "shapeRemove", "jobs", "connections", "logs", "configActive", "configDraft", "configHistory", "configValidate", "configApply", "configRollback"];
};
