declare const normalizeJob: (payload: any) => {
    id: string;
    status: string;
    error: string;
    startedAtSec: number;
    finishedAtSec: number;
    updatedAtSec: number;
} | null;
export type UbuntuProviderState = {
    ok: boolean;
    checkedAtSec?: number;
    nextCheckAtSec?: number;
    sslCacheReady?: boolean;
    sslCacheFresh?: boolean;
    sslRefreshing?: boolean;
    sslRefreshPending?: boolean;
    sslCacheAgeSec?: number;
    sslCacheNextRefreshAtSec?: number;
    providers?: Array<Record<string, any>>;
    job?: ReturnType<typeof normalizeJob>;
    error?: string;
};
export declare const normalizeUbuntuProviderState: (payload: any) => UbuntuProviderState;
export declare const fetchUbuntuProviderChecksAPI: () => Promise<UbuntuProviderState>;
export declare const runUbuntuProviderChecksAPI: () => Promise<UbuntuProviderState>;
export declare const refreshUbuntuProvidersAPI: () => Promise<UbuntuProviderState>;
export declare const refreshUbuntuProviderSslCacheAPI: () => Promise<UbuntuProviderState>;
export declare const fetchUbuntuProviderSslCacheStatusAPI: () => Promise<UbuntuProviderState>;
export type UbuntuSystemStatus = {
    ok: boolean;
    hostname?: string;
    serviceVersion?: string;
    version?: string;
    mihomoVersion?: string;
    mihomoRunning?: boolean;
    serviceStatus?: string;
    serviceUnit?: string;
    platform?: string;
    kernel?: string;
    arch?: string;
    startedAtSec?: number;
    updatedAtSec?: number;
    mihomoLogPath?: string;
    error?: string;
};
export type UbuntuSystemResources = {
    ok: boolean;
    hostname?: string;
    cpuPct?: number;
    load1?: string;
    load5?: string;
    load15?: string;
    memTotalBytes?: number;
    memUsedBytes?: number;
    memAvailableBytes?: number;
    memUsedPct?: number;
    diskTotalBytes?: number;
    diskUsedBytes?: number;
    diskFreeBytes?: number;
    diskUsedPct?: number;
    diskPath?: string;
    uptimeSec?: number;
    kernel?: string;
    arch?: string;
    platform?: string;
    updatedAtSec?: number;
    error?: string;
};
export type UbuntuSystemServiceItem = {
    name: string;
    label?: string;
    description?: string;
    activeState?: string;
    subState?: string;
    enabled?: boolean;
    mainPid?: number;
    sinceSec?: number;
    version?: string;
    error?: string;
};
export type UbuntuSystemServices = {
    ok: boolean;
    items: UbuntuSystemServiceItem[];
    updatedAtSec?: number;
    error?: string;
};
export type UbuntuSystemLogs = {
    ok: boolean;
    source?: string;
    path?: string;
    tail?: number;
    lines?: string[];
    text: string;
    updatedAtSec?: number;
    error?: string;
};
export declare const normalizeUbuntuSystemStatus: (payload: any) => UbuntuSystemStatus;
export declare const normalizeUbuntuSystemResources: (payload: any) => UbuntuSystemResources;
export declare const normalizeUbuntuSystemServices: (payload: any) => UbuntuSystemServices;
export declare const normalizeUbuntuSystemLogs: (payload: any, fallback?: {
    source?: string;
    tail?: number;
}) => UbuntuSystemLogs;
export declare const fetchUbuntuSystemStatusAPI: () => Promise<UbuntuSystemStatus>;
export declare const fetchUbuntuSystemResourcesAPI: () => Promise<UbuntuSystemResources>;
export declare const fetchUbuntuSystemServicesAPI: () => Promise<UbuntuSystemServices>;
export declare const fetchUbuntuSystemLogsAPI: (args?: {
    source?: "mihomo" | "service";
    tail?: number;
}) => Promise<UbuntuSystemLogs>;
export {};
